### ISSUE TITLE
Ordenació incorrecta

### ISSUE THREAD

**Issue by jmontane** [Softcatala/conjugador#10]
L'ordenació no es realitza correctament (posa els caràcters amb diacrítics i el punt volat després de la Z). Vegeu: https://web2015.softcatala.org/conjugador-de-verbs/lletra/A/

És possible que passi en altres ordenacions, no només en els llistats de l'índex?

**Comment by jordimas** [comment]
Joan, jo diria que està solucionat. Mira: https://web2015.softcatala.org/conjugador-de-verbs/lletra/A/

Si no és així re-obre el tiquet si us plau

**Comment by jmontane** [comment]
Sí, ara ordena perfectament.
