### ISSUE TITLE
Quins suggeriments volem?

### ISSUE THREAD

**Issue by jmontane** [Softcatala/conjugador#12]
En escriure en el formulari, què volem suggerir?

Casos:

- L'usuari escriu un text que coincideix amb un infinitiu (cas "coure"). Opcions:
1. Només mostrem els infinitius que hi coincideixen (coure), poden haver-hi més d'un (fer cerca).
2. Mostrem primer els infinitius que hi coincideixen (coure) i després les altres formes flexionades "coure (courar)" (fer autocompleció)

- L'usuari escriu un fragment que **no** coincideix amb un infinitiu (cas "auto"):
Aquí hi ha debat. Què volem? Hi veig 3 opcions:

1.  Mostrar només els infinitius que de les formes que comencen pel text indicat (fer cerca)
2.  Mostrar primer els infinitius que de les formes que comencen pel text indicat (fer cerca) i després les formes flexionades que no són infinitius.
3. Mostrar totes les formes flexionades de tots els verbs. En el cas habitual, les formes d'un únic verb acaparen les primeres posicions del llistat. No és desitjable.

**Comment by jaumeortola** [comment]
Per intentar aclarir conceptes i que els resultats siguin clars per als usuaris. 
* Crec que sempre hauríem de fer una "cerca" i oferir els resultats d'aquesta cerca: una línia davall la caixa de cerca, amb els enllaços més rellevants (almenys quan el resultat no sigui únic).
*  L'autocompleció és un complement secundari d'això. Està bé, però si on es fa (o no es fa bé del tot) no passa res.

**Comment by jordimas** [comment]
Entenc que això ja s'ha solucionat amb els canvis recents. Si no és així, re-obriu el tiquet.
