### ISSUE TITLE
Funcionalitat de cara a l'usuari del conjugador verbal

### ISSUE THREAD

**Issue by xavivars** [Softcatala/conjugador#13]
Des d'un punt de vista funcional, poden existir 4 _tipus_ de pàgines al conjugador verbal.

1. `/conjugador/`: Pàgina principal i de cerca: simplement, mostra el formulari de cerca i els enllaços als index per lletres. El formulari de cerca donaria suggeriments, que idealment anirien a la pàgina 4, o permetria fer una cerca lliure, que aniria a la pàgina 3
1. `/conjugador/lletra/X` Pàgina d'index: Mostra una llista de tots els verbs que comencen per una lletra determinada
1. `/conjugador/cerca/xxxx` Pàgina de cerca (opcional): en aquells casos on _xxxx_ corresponga a formes flexionades de més d'un verb, la pàgina mostraria enllaços a tots els verbs (que anirien a la pàgina 4). En cas que només corresponga a un verb, la pàgina de cerca redigiria directament a la pàgina 4
1. `/conjugador/verb/xxxx` Pàgina de flexió verbal, on _xxxx_ és un infinitiu. Mostra les formes flexionades d'un verb determinat.

_____________________________________

Coses que queden a implementar:
* [x] (backend) Per a poder anar de la pàgina 1 a la 4 amb l'autocompleció, cal que la informació de l'infinitiu estiga disponible en eixe API. (https://github.com/Softcatala/conjugador/pull/11 era una primera aproximació a la implementació)
* [ ] (frontend) Cal crear una nova pàgina, `/conjugador/cerca/xxxx`, que siga no indexable, i que en cas de que el resultat de l'API de cerca torne només un resultat, redirigisca a la pàgina 4. Sinó, ha de mostrar les diferents opcions
* [ ] (frontend) Cal canviar `/conjugador/verb/xxxx` per a que funcione només amb infinitius: si la _xxxx_ no correspon a un infinitiu, la pàgina ha de tornar un error 404.

**Comment by jaumeortola** [comment]
Casos típics que s'haurien de comprovar:
https://www.softcatala.org/api/conjugadorsearch/coure
https://www.softcatala.org/api/conjugadorsearch/cou
https://www.softcatala.org/api/conjugadorsearch/auto
https://www.softcatala.org/api/conjugadorsearch/argu

https://www.softcatala.org/api/conjugador/autocomplete/coure
https://www.softcatala.org/api/conjugador/autocomplete/cou
https://www.softcatala.org/api/conjugador/autocomplete/auto
https://www.softcatala.org/api/conjugador/autocomplete/argu

**Comment by jaumeortola** [comment]
Hi ha una possibilitat de mostrar les pàgines /conjugador/cerca/xxxx sense que hi hagi continguts repetits. Ho deixo apuntat per si ho volem considerar. Seria donar en primer lloc la informació concreta de la forma, i després la conjugació de tot el verb. Per exemple, /conjugador/cerca/fora:

```
fora: 
1a i 3a persona del condicional del v. ser
1a i 3a persona de l'imperfet de subjuntiu del v. ser (valencià)

Ser
Present d'indicatiu
jo sóc...
...
```

**Comment by jordimas** [comment]
Entenc que això ja està implementat.
