### ISSUE TITLE
Infinitius secondaris en el llistat de verbs

### ISSUE THREAD

**Issue by jordimas** [Softcatala/conjugador#19]
Alguns infintius tenen més d'una forma. Per exemple:

abstenir / abstindre
abstraure / abstreure

En aquests casos ens cal saber quina és la forma principal

Ara mateix l'API de llista torna una llista de verbs en infintius. Caldria incloure en els casos on calgués múltiples formes la principial en la informació que es retorna

Per exemple, per l'entrada "abstindre" hauríem d'indicar que abstenir és la forma principal

**Comment by mpiulats** [comment]
Client actualitzat.

**Comment by jordimas** [comment]
Solventat
