### ISSUE TITLE
Presentar les variants sempre en el mateix ordre

### ISSUE THREAD

**Issue by jaumeortola** [Softcatala/conjugador#2]
L'ordre que podríem fer és el següent. No sé exactament en quin lloc del codi s'ha de posar.

0
C
X
Y
Z
V
B
1
2
3
4
5
6
7

**Comment by jordimas** [comment]
Jaume, entenc que l'ordre actual és:

0
X
Y
Z
C
V
B
1
2
3
4
5
6
7

Correcte?

Jordi,

**Comment by jaumeortola** [comment]
Sí, és això el que passa. P. ex. `sofregesc / sofrig (val,bal), sofregeixo, sofregisc / sofrigc (val)`

És aquí on es decideix l'ordre, no?
https://github.com/Softcatala/conjugador/blob/master/extractor/extract.py#L75

**Comment by jordimas** [comment]
Correcte. Entenc llavors que això soluciona el problema:

https://github.com/Softcatala/conjugador/commit/4b5bd76df9fca2acbfd703334b498177e0b7b57f

El que no entenc és perquè el títol de l'informe d'error és "Presentar les variants sempre en el mateix ordre" perquè ja es presenten en ordre, el que entenc que succeïx és que no és l'ordre que considerem adient.

**Comment by jaumeortola** [comment]
> El que no entenc és perquè el títol de l'informe d'error és "Presentar les variants sempre en el mateix ordre" perquè ja es presenten en ordre, el que entenc que succeïx és que no és l'ordre que considerem adient.

Disculpa la manca de precisió ;-). Però és que jo no sabia ni què feia el teu codi.

**Comment by jordimas** [comment]
Cap problema ho preguntava per assegurar-me que no em deixava res.

Ho pujo a producció després i quan ho verifiquem allà tanquem el tiquet.

**Comment by jaumeortola** [comment]
> Correcte. Entenc llavors que això soluciona el problema:
> 
> [4b5bd76](https://github.com/Softcatala/conjugador/commit/4b5bd76df9fca2acbfd703334b498177e0b7b57f)

Sí, això és.

**Comment by jaumeortola** [comment]
Ja es veu arreglat en la web.
