### ISSUE TITLE
Algunes formes que estan al diccionari font no s'haurien de mostrar

### ISSUE THREAD

**Issue by jordimas** [Softcatala/conjugador#20]
**Problema**

Algunes formes que estan al diccionari font no s'haurien de mostrar:

 "só ser VSIP1S00" (aquesta és molt evident ja que és al verb ser)

**Possible solució**

Crear una llista negra que l'extractor ja no exportaria.

**Comment by jaumeortola** [comment]
De fet, ja he eliminat el "só". L'única utilitat que tindria és per a analitzar texts antics. Els últims commits són de petites correccions en els verbs. 

No sé si n'hi ha més. 

Una qüestió dubtosa és la dels accents diacrítics que han desaparegut. Ara els mostrem tots dos. Es pot quedar així o ho podem indicar d'alguna manera (p. ex. un asterisc que digui "abans de la reforma tal...").
