### ISSUE TITLE
Petita descripció del significat de cada verb

### ISSUE THREAD

**Issue by Ecron** [Softcatala/conjugador#21]
Podríem importar d'algun diccionari lliure una petita descripció general del significat dels verbs. Potser la primera accepció si hi ha més d'una, i enllaçar a la font per a veure'n més.

**Comment by jmontane** [comment]
Com a primer pas, podríem afegir enllaços a l'entrada del verb corrresponent en web de consulta: Viccionari, DIEC, DNV, Enciclopèdia. Un dels problemes és que un verb del conjugador no té perquè estar recollit en tots i cadascún dels webs anteriors. De fet, potser en cap. Per tant, hauríem d'afegir les fonts on podem trobar els verbs a les dades del json.

**Comment by pereorga** [comment]
> Podríem importar d'algun diccionari lliure una petita descripció general del significat dels verbs. Potser la primera accepció si hi ha més d'una, i enllaçar a la font per a veure'n més.

Crec que això ja es va fer (es va importar el Viccionari)


> Com a primer pas, podríem afegir enllaços a l'entrada del verb corrresponent en web de consulta: Viccionari, DIEC, DNV, Enciclopèdia. Un dels problemes és que un verb del conjugador no té perquè estar recollit en tots i cadascún dels webs anteriors. De fet, potser en cap. Per tant, hauríem d'afegir les fonts on podem trobar els verbs a les dades del json.

Em sembla que això ja té un altre tiquet: https://github.com/Softcatala/conjugador/issues/23

(és, a dir, crec que es pot tancar aquest)

**Comment by jordimas** [comment]
Sí, al conjugador hi ha una pestanya amb les definicions que importem del Viccionari. Anem important-les cada cert temps, ara tenim al voltant del 50% dels termes amb definició.
