### ISSUE TITLE
Estandaritzar formes als llistats dels verbs

### ISSUE THREAD

**Issue by jordimas** [Softcatala/conjugador#30]
**Problema**
- Alguns verbs tenen diferents infitinius. Per exemple abstenir té "abstenir" i "abstindre".  Usem com a forma a mostrar a l'usuari la que en el fitxer diccionari.txt està la 2 segona columna com infitiniu de totes les formes
- A la pàgina d'índex de lletres https://www.softcatala.org/conjugador-de-verbs/lletra/A/ tenim per exemple al text que mostrem  "abstindre" i l'enllaç a https://www.softcatala.org/conjugador-de-verbs/verb/abstenir/

**Canvi proposat**

En la meva opinió si la forma per a referir-nos al verb és abstenir no té cap sentit tenir mostrar "abstindre" (una forma secundària) i hauríem de mostrar la forma primaria que a més és la de l'enllaç. 

Aquesta pàgina és perquè els cercadors trobin la pàgina però això simplificaria també el codi.

**Comment by jaumeortola** [comment]
Què vols fer exactament? Eliminar abstindre de la llista lletra/A? Per simplicitat? Els verbs s'haurien de poder trobar per totes les formes. No fa cap mal que es trobin per diferents vies.

**Comment by jordimas** [comment]
Hola Jaume. Aquesta pàgina és només per cercadors. Ara mateix només tenim una URL per pàgina, perquè és com els cercadors ho volen. Llavors en aquesta pàgina només hi ha una entrada per verb, ja que per tenir-ne més caldria fer-ne més URL i això per SEO no ho volen. Només una URL única.

El que suggereixo és molt senzill que nom del verb al text coincideixi amb el de l'enllaç.

Ara tenim: text: abstindre, enllaç: https://www.softcatala.org/conjugador-de-verbs/verb/abstenir/

I tenim codi al Wordpress condicional i a la web per poder fer això. Per mi és més correcte (i ens permet simplificar el codi), fer:

text: abstenir, enllaç: https://www.softcatala.org/conjugador-de-verbs/verb/abstenir/

Si tens cap dubte em dius

**Comment by jaumeortola** [comment]
Si els cercadors ho trobaran igual amb abstenir i abstindre, cap problema.

**Comment by xavivars** [comment]
Jo no ho veig així. Els si eliminem abstindre del llistat, estem llevant indicadors de que abstenir i abstindre són el mateix.

**Comment by jordimas** [comment]
No eliminem res del llistat, no caviem nomes canviem el **text**.  El meu últim comentari explica en detall el canvi.

**Comment by xavivars** [comment]
Si he entés bé el teu comentaris, ara tenim dos enllaços, un amb abstenir, i un altre amb abstindre, que van a la mateixa pàgina. I amb la proposta, només n'hi haurà un, abstenir.

És així?

**Comment by jordimas** [comment]
No, només hi ha un enllaç. 

Per verbs on hi ha més d'una forma d'infinitiu, seleccionem una per al text diferent que la que usem per l'enllaç, i el que suggereixo és el que **text**  digui el mateix de l'enllaç ja que tenim tota una  lògica per fer això que penso no és necessari. 

És a dir, ara tenim

text: abstindre
enllac: https://www.softcatala.org/conjugador-de-verbs/verb/abstenir

En comptes fer:

text: abstenir
enllac: https://www.softcatala.org/conjugador-de-verbs/verb/abstenir

Només canviem el text, el que ens permet simplificar la lògica.

**Comment by jordimas** [comment]
Tens raó Jaume. M'he confòs. Tenia una còpia en local amb uns canvis que feian que el comportament no fos el de producció. Tanco el tiquet llavors. Sap greu per la confusió.
