### ISSUE TITLE
No tots els verbs auto* són reflexius

### ISSUE THREAD

**Issue by jmontane** [Softcatala/conjugador#31]
No tots els verbs que comencen per "auto" són reflexius.

Ho comento per [aquesta condició](https://github.com/Softcatala/conjugador/blob/reflexius3/extractor/reflexius.py#L42).

P. ex, "automatitzar" i "autoritzar", segur que **no** són reflexius. Considerar-los reflexius al conjugador és un error.

Altres casos són més dubtosos, suposo que depèn de la font de referència. P. ex. "autofinançar", "autogestionar", "autografiar" i "autoeditar" tenen entrada en el DIEC o en el DNV sense ser reflexius.

Però el que digui el @jaumeortola :)

**Comment by jaumeortola** [comment]
Les excepcions ara en LT són: `autografiar|automatitzar|autoritzar|autogestionar|autoeditar`.

**Comment by jmontane** [comment]
Solucionat [aquí](https://github.com/Softcatala/conjugador/commit/1e5e2150ede49febdd78c5af68e7edea1287f546). Tanco el tiquet
