### ISSUE TITLE
No es mostren definicions per als verbs reflexius

### ISSUE THREAD

**Issue by jmontane** [Softcatala/conjugador#33]
El Conjugador no ofereix definició per als verbs reflexius (p. ex. [colltrencar](https://www.softcatala.org/conjugador-de-verbs/verb/colltrencar/) , no troba cap definició en l'article del Viccionari [colltrencar](https://ca.wiktionary.org/wiki/colltrencar), perquè no té cap definició. I és normal que no la tingui, perquè l'article principal al Viccionari és [colltrencar-se](https://ca.wiktionary.org/wiki/colltrencar-se) (en ser un verb reflexiu).

En resum, en els verb reflexius, caldria cercar primer la definició en els articles de l'infinitiu amb pronom (colltrencar-se) i, si no existeix l'article, aleshores mirar l'article sense pronom (colltrencar).

**Comment by jordimas** [comment]
Aquesta errada causa que no importem 216 definicions que podríem impotar. Aquesta errada és anterior a la introducció dels reflexius al diccionari, ja que al Wiktionary sempre hem buscat l'infitiniu ja que no ens havíem adonat d'això. Ho esmenaré.

**Comment by jordimas** [comment]
Solucionat a producció
