### ISSUE TITLE
Remissions: definicions que es perden en l'extracció.

### ISSUE THREAD

**Issue by jmontane** [Softcatala/conjugador#37]
Al Viccionari, alguns verbs només tenen com a definició una remissió a un altre verb. Aquestes definicions no les exportem al Conjugador perquè estan generades amb una plantilla {{forma-a|ca|...}}, que suprimim en l'extracció de les definicions.

Alguns exemples:
- [assadollar](https://ca.wiktionary.org/wiki/assadollar) > sadollar
- [acurçar](https://ca.wiktionary.org/wiki/acur%C3%A7ar) > escurçar
- [corregnar](https://ca.wiktionary.org/wiki/corregnar) > coregnar
- [decolorar](https://ca.wiktionary.org/wiki/decolorar) > descolorir

El cas de 'corregnar' és curiós: el Viccionari té com a preferent, amb definicions, la forma 'coregnar'. I 'corregnar' remet a 'coregnar'. Al Conjugador, però, només recollim 'corregnar', sense definició pel problema descrit en aquest tiquet.

**Comment by jordimas** [comment]
Vegeu també la documentació de la plantilla: https://ca.wiktionary.org/wiki/Plantilla:forma-a

**Comment by jmontane** [comment]
He fet un petit retoc al codi per a substituir les plantilles {{forma-a|ca per una marca. Es passa de 6336 definicions i 3871 verbs sense cap definició a 6485 defincions i 3721 verbs sense definició. Guanyaríem definicions per a 150 verbs.

Tot això només ho faria si al Viccionari el verb només té com a definició la plantilla {{forma|ca|- }}. És a dir, si no té contingut textual net a les definicions. Els verbs principals (p. ex "sadollar") tenen remissió (cap a 'assadollar') i definicions textuals. No tinc clar si també hauríem d'enllaçar des de la forma principal (sadollar) cap a la secundària (assadollar).

El que proposo:
- Posar el mateix text que al Viccionari (expandir la plantilla): "Forma alternativa de ....".
- Idealment, enllaçar cap al verb principal (com al Viccionari) i que remeti a la definició del verb principal en el Conjugador, sempre que el tinguem al Conjugador, és clar.

**Comment by jmontane** [comment]
Jordi, [aquí](https://pastebin.com/27FNXgti) hi ha un pedaç que tracta la plantilla {{forma|ca|..} i també {{marca|ca|...} que hi ha a les definicions. Amb això passem a 6491 definicions i 3715 verbs sense definicions.

**Comment by jordimas** [comment]
He fet una proposta de solució a: https://github.com/Softcatala/conjugador/pull/39

Inclou totes les dades que canvien

**Comment by jordimas** [comment]
Et comento

1. No hauria de ser un problema
2. Ho deixem pel futur, ja són prou canvis de moment

**Comment by jordimas** [comment]
Pujat a producció, gràcies!
