### ISSUE TITLE
Definicions amb restes de codi mediawiki/html

### ISSUE THREAD

**Issue by jmontane** [Softcatala/conjugador#38]
Algunes definicions tenen restes de codi mediawiki/html que es mostren en el web. Adjunto 3 captures d'exemple

Els verbs afectats que he pogut trobar són:

- cofinançar
- desembargar
- diferenciar
- domar
- embadalir
- fotre
- lluir
- onejar
- psicoanalitzar
- rapejar
- reanomenar
- reinserir
- seguir
- sotaposar
- virtualitzar
- 
![error-onejar](https://github.com/Softcatala/conjugador/assets/339645/eb8f13af-87f3-4b5e-88c9-11965910476d)
![error-cofinançar](https://github.com/Softcatala/conjugador/assets/339645/77cba880-1bba-4ff6-932a-6ed75caa00c7)
![error-desembargar](https://github.com/Softcatala/conjugador/assets/339645/462ccee8-4451-4df9-b977-8fccad029c30)

**Comment by jordimas** [comment]
Hola Joan. Aquí hi ha el filtratge que es fa:

https://github.com/Softcatala/conjugador/blob/master/definitions/textextract.py#L170

I aquí les proves unitàries que fem:
https://github.com/Softcatala/conjugador/blob/master/definitions/test/testtextextract.py

Que clarament és incomplet. Si pots proposar millores en forma de canvis o expressions regulars que caldria afegir-hi seria de molta d'ajuda.

**Comment by jordimas** [comment]
Pujat a producció. Si veieu alguna cosa que queda m'ho dius. Si no, tanquem el tiquet.

**Comment by jmontane** [comment]
Ho veig tot bé. Tanco el tiquet.
