### ISSUE TITLE
Verbs amb més d'un infinitiu

### ISSUE THREAD

**Issue by jmontane** [Softcatala/conjugador#4]
Ara mateix, usem com a títol/capçalera el valor del json del verb, que és l'id que usa Languagetool, i es correspon amb l'infinitiu. Hi ha casos on el verb pot tenir més d'un infinitiu (p. ex. jaure / jeure). En aquests casos, habitualment es presenta el verb amb la doble forma (no sempre,  el conjugador l'Enciclopèdia, per exemple, no ho fa). Ara mateix l'efecte pot quedar estrany:
![infinitiu](https://user-images.githubusercontent.com/339645/80467685-7d37ad80-893e-11ea-851c-c18164bd36cf.png)

![jaure](https://user-images.githubusercontent.com/339645/80467644-67c28380-893e-11ea-871a-590e316d78b7.png)

Exemple a Optimot
![jeure_o_jaure](https://user-images.githubusercontent.com/339645/80467505-2cc05000-893e-11ea-9b52-323d297c1e41.png)

Com a cas general, crec que el que mostrem al camp "infinitiu" hauria de coincidir amb el títol que usem.

**Comment by jordimas** [comment]
@mpiulats Entenc que aquest és un tema de presentació i no que que jo toqui res

**Comment by jaumeortola** [comment]
Resolt
![imatge](https://user-images.githubusercontent.com/4289501/80527035-075e3100-8994-11ea-831a-cc3cb9f9c3a2.png)

Encara que hi ha algun cas especial:
![imatge](https://user-images.githubusercontent.com/4289501/80527100-21980f00-8994-11ea-94a5-4a221cfaa497.png)

Jo ho veig bé com està.

**Comment by jmontane** [comment]
Ho donem per tancat.
