### ISSUE TITLE
Verbs amb doble participi -ès / -és (p. ex. «cometre»)

### ISSUE THREAD

**Issue by jmontane** [Softcatala/conjugador#41]
En els verbs amb doble participi amb canvi d'accentuació (una formada en -ès i una altra acabada en -és, pròpia del valencià), per exemple «[cometre](https://www.softcatala.org/conjugador-de-verbs/verb/cometre/)», en el Conjugador mostrem els dos participis concatenats amb una barra «comès / comés», sense cap marca de variació dialectal (perquè a les dades del corrector no hi és aquesta informació, ja que es gestiona d'una altra forma). Això pot generar confusió, especialment per als aprenents de català.

Aquest problema no apareix en la majoria de webs amb flexió verbal, perquè només mostren un participi.

- [GIEC](https://giec.iec.cat/conjugacio/verb/14570?verb=cometre&codi=14570) (només mostra «comès»)
- [DIEC](https://dlc.iec.cat/Verbs?IdE=0014570) (només mostra «comès»)
- [GDLC](https://www.diccionari.cat/conjugador_catala/cometre#) (només mostra «comès»)
- [DNV](https://www.avl.gva.es/lexicval/?paraula=cometre) (només mostra «comés»).
- [Viccionari](https://ca.wiktionary.org/wiki/cometre) (mostra els dos participis «comès o comés»)

Crec que hauríem de marcar el participi «comés» d'alguna forma, que eviti que els usuaris amb pocs coneixements dialectals considerin les dues formes equivalents. Ara per ara, el conjugador no aporta cap informació per a triar-ne una o l'altra.

Un hack possible (segurament no és ideal) és que, durant l'extracció de dades del conjugador, només per als casos de participis amb doble accentuació, en formar el cadena «comès / comés» marcar aquesta forma construïda com a valenciana. D'aquesta manera en el web hauria de quedar com a «comès / comés (val.)»

![cometre-perfet](https://github.com/Softcatala/conjugador/assets/339645/9d385daf-4e65-4fcd-81fc-f8461b0f2ce7)
![cometre-Formes_no_personals](https://github.com/Softcatala/conjugador/assets/339645/d69d6dee-a988-4fd0-b01c-e21ace765752)
![cometre-GIEC](https://github.com/Softcatala/conjugador/assets/339645/3bfcab7d-c77d-4503-8ba7-743412a267ea)
![cometre-DNV-perfet](https://github.com/Softcatala/conjugador/assets/339645/82239699-ba3f-46a5-b514-0067837fb771)
![cometre-DNV](https://github.com/Softcatala/conjugador/assets/339645/06770074-e3b2-4854-bda8-fa1e67714db8)

**Comment by jaumeortola** [comment]
Aquí hi ha la llista de totes les accentuacions dobles en els verbs. 
* en el participi masculí singular ès/és (65 casos) 
* alguns infinitius èixer/éixer (12 casos). 

Trobo que no em deixo res. Però amb la conjugació verbal no se sap mai.

```
$ grep "és .* V.P" *.txt 

acomés acometre VMP00SM0
admés admetre VMP00SM0
aprehés aprehendre VMP00SM0
aprés aprendre VMP00SM0
arremés arremetre VMP00SM0
atés atendre VMP00SM0
atés atènyer VMP00SM0
compromés comprometre VMP00SM0
comprés comprendre VMP00SM0
comés cometre VMP00SM0
contés contendre VMP00SM0
corprés corprendre VMP00SM0
defés defendre VMP00SM0
demés demetre VMP00SM0
deprés deprendre VMP00SM0
depés dependre VMP00SM0
desaprés desaprendre VMP00SM0
desatés desatendre VMP00SM0
descompromés descomprometre VMP00SM0
desentés desentendre VMP00SM0
després desprendre VMP00SM0
despés despendre VMP00SM0
destés destendre VMP00SM0
distés distendre VMP00SM0
emprés emprendre VMP00SM0
empés empènyer VMP00SM0
emés emetre VMP00SM0
encés encendre VMP00SM0
entremés entremetre VMP00SM0
entés entendre VMP00SM0
escomés escometre VMP00SM0
espés espènyer VMP00SM0
estés estendre VMP00SM0
expés expendre VMP00SM0
fideïcomés fideïcometre VMP00SM0
hiperestés hiperestendre VMP00SM0
imprés imprimir VMP00SM0
inadmés inadmetre VMP00SM0
malentés malentendre VMP00SM0
malmés malmetre VMP00SM0
malprés malprendre VMP00SM0
mamprés mamprendre VMP00SM0
manumés manumetre VMP00SM0
ofés ofendre VMP00SM0
omés ometre VMP00SM0
permés permetre VMP00SM0
pretés pretendre VMP00SM0
promés prometre VMP00SM0
readmés readmetre VMP00SM0
reaprés reaprendre VMP00SM0
reemés reemetre VMP00SM0
reimprés reimprimir VMP00SM0
remés remetre VMP00SM0
représ reprendre VMP00SM0
retransmés retransmetre VMP00SM0
salprés salprendre VMP00SM0
sobreentés sobreentendre VMP00SM0
sobreimprés sobreimprimir VMP00SM0
sobreprés sobreprendre VMP00SM0
sorprés sorprendre VMP00SM0
sotmés sotmetre VMP00SM0
suspés suspendre VMP00SM0
tramés trametre VMP00SM0
transmés transmetre VMP00SM0
ullprés ullprendre VMP00SM0


$ grep "éixer.*èixer" *.txt 
amanéixer amanèixer VMN00000
aparéixer aparèixer VMN00000
comparéixer comparèixer VMN00000
conéixer conèixer VMN00000
desaparéixer desaparèixer VMN00000
desconéixer desconèixer VMN00000
desmeréixer desmerèixer VMN00000
iréixer irèixer VMN00000
meréixer merèixer VMN00000
paréixer parèixer VMN00000
reaparéixer reaparèixer VMN00000
reconéixer reconèixer VMN00000
```

**Comment by jordimas** [comment]
Hola!

Ja està solucionat.  Vegeu: https://www.softcatala.org/conjugador-de-verbs

Comentar que les formes següents no les tenim al conjugador:
diccionari-dnv.txt:acomés acometre VMP00SM0
diccionari-dnv.txt:destés destendre VMP00SM0
diccionari-dnv.txt:amanéixer amanèixer VMN00000
